targetNamespace: ''
parameters: {}
packages:
  - name: chores
    environment: {}
    parameters: {}
    annotations: {}
    actions:
      - name: chore_texts
        binary: false
        runtime: 'python:default'
        web: true
        parameters: {}
        environment:
          PEOPLE: "${PEOPLE}"
          TWILIO_ACCOUNT_SID: "${TWILIO_ACCOUNT_SID}"
          TWILIO_AUTH_TOKEN: "${TWILIO_AUTH_TOKEN}"
          TWILIO_PHONE_NUMBER: "${TWILIO_PHONE_NUMBER}"
        annotations: {}
        limits: {}
